### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by ProxiBlue**
add version constraint to magento framework to ensure this version is not installed pre m2.4.6

### CODE REVIEW

**Comment by magiccart** [comment]
Hi @ProxiBlue 
Thanks for your contribution. I have update code to compatible with latest version 2.4.6 and old version so I think don't need merger this right?

**Comment by ProxiBlue** [comment]
Hey @magiccart  - not sure what you updated, but if you feel this is not needed, no problem. Just want to make sure pre m2.4.6 sites with non locked down composer don't pull in the 2.4.6 code, and break sites.


mainly due to this change: https://github.com/magepow/magento-2-categories/pull/15

**Comment by magiccart** [comment]
I updated file system.xml without require Magepow\Categories\Model\Config\Heading and remove this file you check in commit https://github.com/magepow/magento-2-categories/commit/3c6d6d790d8d0e65a84d9d0eaa66fcbd3229f1b7

**Comment by ProxiBlue** [comment]
Ok, so yo had taken out the code that vailidates the textual in heading. Your module, so if you ok tyo go with out that, i will close this MR

**Pull request closed without merging**
